# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ponga_config = debug

else ifeq ($(config),release)
  ponga_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ponga

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ponga:
ifneq (,$(ponga_config))
	@echo "==== Building ponga ($(ponga_config)) ===="
	@${MAKE} --no-print-directory -C . -f ponga.make config=$(ponga_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f ponga.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ponga"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"